"""create prompt tables - initial schema for prompt engineering module

Revision ID: 001
Revises:
Create Date: 2026-07-21

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust where ###

    # Table 1: prompt_templates
    op.create_table('prompt_templates',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=False, server_default='system'),
        sa.Column('owner', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='active'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pt_name', 'prompt_templates', ['name'], unique=True)
    op.create_index('idx_pt_status', 'prompt_templates', ['status'], unique=False)

    # Table 2: prompt_versions
    op.create_table('prompt_versions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('template_id', sa.Integer(), nullable=False),
        sa.Column('version', sa.String(length=50), nullable=False),
        sa.Column('semver_major', sa.Integer(), server_default='0', nullable=False),
        sa.Column('semver_minor', sa.Integer(), server_default='0', nullable=False),
        sa.Column('semver_patch', sa.Integer(), server_default='0', nullable=False),
        sa.Column('semver_prerelease', sa.String(length=50), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('variables_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'),
        sa.Column('system_role', sa.Text(), nullable=True),
        sa.Column('changelog', sa.Text(), nullable=True),
        sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('released_by', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'),
        sa.Column('latest_eval_score', sa.Float(), nullable=True),
        sa.Column('eval_dataset_hash', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('template_id', 'version', name='unique_template_version')
    )
    op.create_index('idx_pv_template', 'prompt_versions', ['template_id'], unique=False)
    op.create_index('idx_pv_semver', 'prompt_versions', ['semver_major', 'semver_minor', 'semver_patch'], unique=False)
    op.create_index('idx_pv_status', 'prompt_versions', ['status'], unique=False)

    # Table 3: prompt_tags
    op.create_table('prompt_tags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('template_id', sa.Integer(), nullable=False),
        sa.Column('tag_name', sa.String(length=50), nullable=False),
        sa.Column('version_id', sa.Integer(), nullable=False),
        sa.Column('meta_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'),
        sa.Column('updated_by', sa.String(length=255), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['version_id'], ['prompt_versions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('template_id', 'tag_name', name='unique_template_tag')
    )
    op.create_index('idx_ptag_template', 'prompt_tags', ['template_id'], unique=False)
    op.create_index('idx_ptag_name', 'prompt_tags', ['tag_name'], unique=False)

    # Table 4: test_cases
    op.create_table('test_cases',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('template_id', sa.Integer(), nullable=False),
        sa.Column('input_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('expected_output', sa.Text(), nullable=True),
        sa.Column('expected_behavior', sa.Text(), nullable=True),
        sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'),
        sa.Column('priority', sa.Integer(), server_default='1', nullable=False),
        sa.Column('is_active', sa.Integer(), server_default='1', nullable=False),
        sa.Column('created_by', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tc_template', 'test_cases', ['template_id'], unique=False)
    op.create_index('idx_tc_priority', 'test_cases', ['priority'], unique=False)

    # Table 5: eval_runs
    op.create_table('eval_runs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('version_id', sa.Integer(), nullable=False),
        sa.Column('baseline_version_id', sa.Integer(), nullable=True),
        sa.Column('test_case_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('avg_score', sa.Float(), nullable=True),
        sa.Column('pass_count', sa.Integer(), nullable=True),
        sa.Column('fail_count', sa.Integer(), nullable=True),
        sa.Column('total_count', sa.Integer(), nullable=True),
        sa.Column('detailed_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'),
        sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('triggered_by', sa.String(length=50), nullable=False),
        sa.Column('run_duration_ms', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.ForeignKeyConstraint(['version_id'], ['prompt_versions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['baseline_version_id'], ['prompt_versions.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_er_version', 'eval_runs', ['version_id'], unique=False)
    op.create_index('idx_er_run_at', 'eval_runs', ['run_at'], unique=False)

    # Table 6: prompt_audit_logs
    op.create_table('prompt_audit_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('actor', sa.String(length=255), nullable=False),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('resource_type', sa.String(length=50), nullable=False),
        sa.Column('resource_id', sa.Integer(), nullable=False),
        sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor', 'prompt_audit_logs', ['actor'], unique=False)
    op.create_index('idx_audit_action', 'prompt_audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_resource', 'prompt_audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_time', 'prompt_audit_logs', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust where ###
    op.drop_index('idx_audit_time', table_name='prompt_audit_logs')
    op.drop_index('idx_audit_resource', table_name='prompt_audit_logs')
    op.drop_index('idx_audit_action', table_name='prompt_audit_logs')
    op.drop_index('idx_audit_actor', table_name='prompt_audit_logs')
    op.drop_table('prompt_audit_logs')

    op.drop_index('idx_er_run_at', table_name='eval_runs')
    op.drop_index('idx_er_version', table_name='eval_runs')
    op.drop_table('eval_runs')

    op.drop_index('idx_tc_priority', table_name='test_cases')
    op.drop_index('idx_tc_template', table_name='test_cases')
    op.drop_table('test_cases')

    op.drop_index('idx_ptag_name', table_name='prompt_tags')
    op.drop_index('idx_ptag_template', table_name='prompt_tags')
    op.drop_table('prompt_tags')

    op.drop_index('idx_pv_status', table_name='prompt_versions')
    op.drop_index('idx_pv_semver', table_name='prompt_versions')
    op.drop_index('idx_pv_template', table_name='prompt_versions')
    op.drop_table('prompt_versions')

    op.drop_index('idx_pt_status', table_name='prompt_templates')
    op.drop_index('idx_pt_name', table_name='prompt_templates')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
