"""add synonym and desensitization tables

Revision ID: 007
Revises: 006
Create Date: 2026-07-29

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007'
down_revision = '006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create synonyms table
    op.create_table(
        'synonyms',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('standard_term', sa.String(255), nullable=False),
        sa.Column('synonyms_json', sa.Text(), nullable=False),
        sa.Column('category', sa.String(100), nullable=True),
        sa.Column('kb_id', sa.String(36), nullable=True),
        sa.Column('is_enabled', sa.Boolean(), default=True),
        sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synonyms_standard_term'), 'synonyms', ['standard_term'], unique=False)
    op.create_index(op.f('ix_synonyms_category'), 'synonyms', ['category'], unique=False)
    op.create_index(op.f('ix_synonyms_kb_id'), 'synonyms', ['kb_id'], unique=False)
    op.create_index(op.f('ix_synonyms_is_enabled'), 'synonyms', ['is_enabled'], unique=False)

    # Create desensitization_config table
    op.create_table(
        'desensitization_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('kb_id', sa.String(36), nullable=True),
        sa.Column('level', sa.String(20), default='medium'),
        sa.Column('enable_email_mask', sa.Boolean(), default=True),
        sa.Column('enable_phone_mask', sa.Boolean(), default=True),
        sa.Column('enable_id_card_mask', sa.Boolean(), default=True),
        sa.Column('enable_bank_card_mask', sa.Boolean(), default=True),
        sa.Column('enable_address_mask', sa.Boolean(), default=False),
        sa.Column('enable_name_mask', sa.Boolean(), default=False),
        sa.Column('custom_replacements_json', sa.String(4096), nullable=True),
        sa.Column('mask_char', sa.String(10), default='*'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desensitization_config_kb_id'), 'desensitization_config', ['kb_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_desensitization_config_kb_id'), table_name='desensitization_config')
    op.drop_table('desensitization_config')

    op.drop_index(op.f('ix_synonyms_is_enabled'), table_name='synonyms')
    op.drop_index(op.f('ix_synonyms_kb_id'), table_name='synonyms')
    op.drop_index(op.f('ix_synonyms_category'), table_name='synonyms')
    op.drop_index(op.f('ix_synonyms_standard_term'), table_name='synonyms')
    op.drop_table('synonyms')
    # ### end Alembic commands ###
