"""remove_provider_is_default

Revision ID: 010
Revises: 009
Create Date: 2026-08-03 14:05:33

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010'
down_revision: Union[str, None] = '009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """删除 model_providers 表的 is_default 字段"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_providers', 'is_default')
    # ### end Alembic commands ###


def downgrade() -> None:
    """恢复 is_default 字段"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_providers', sa.Column('is_default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
